CREATE TABLE moment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    type        VARCHAR(50)   NOT NULL,
    target_date DATE,
    start_time  TIMESTAMP,
    image_url   VARCHAR(500),
    description VARCHAR(1000),
    color       VARCHAR(50),
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL
);
